services:
  - type: web
    name: motoropolis
    runtime: static
    repo: https://github.com/WiltonSilva-Backend/Motoropolis
    branch: webgl-build
    staticPublishPath: .
    autoDeployTrigger: commit
