name: Request Unity activation file

on:
  workflow_dispatch:

jobs:
  activation:
    name: Request manual activation file
    runs-on: ubuntu-latest

    steps:
      - name: Request manual activation file
        id: activation
        uses: game-ci/unity-request-activation-file@v2

      - name: Publish activation file
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.activation.outputs.filePath }}
          path: ${{ steps.activation.outputs.filePath }}
